baseURL = "/"
languageCode = "de-de"
title = "COMPASS"
#theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
#googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "de"

# TODO: check functionality in current theme
# These "images" are used for the structured data templates. This will show up, when
# services like Twitter or Slack want to generate a preview of a link to your site.
# See https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph.
images = ["images/NUM_compass.png", "images/NUM_Compass.svg", "images/NUM_logo.png"]

# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "de"
[[Params.listeLangues]]
code = "en"


# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font


[module]
  [[module.imports]]
    path = "github.com/themefisher/navigator-hugo"