weight = 1
languageCode = "de-de"
languageName = "deutsch"
contentDir = "content/de"
#title = "English title"

# dateFormat is only working in English language!
dateFormat = "02. 02. 2006"

# Site Params
[params]
    logo = "images/logo.svg"
    menufixed = false

    # meta data
    author = "Michael Stach"
    description = "Coordination on mobile pandemic apps best practice and solution sharing"

    # TODO: Include in current theme
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© 2020, NUM-COMPASS team"
    keywords = "mobile, pandemic, app, covid, covid19, corona, netzwerk universitätsmedizin, universitätsmedizin"

    # TODO: Include in current theme
    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "favicon-96x96.png"

    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerFundingTitle = "Förderung"

    footerSocialTitle = "Social Media"
    footerSocialText = "Wir halten Sie auf dem Laufenden! Abbonnieren Sie unseren Kanal auf den folgenden Plattformen:"
    footerSocialTwitter = "https://twitter.com/CompassNum/"

    # Hero Area Section
    [params.hero]
    enable  = true
    heading = "Bewährte Praktiken und gemeinsame Lösungen für mobile Pandemie-Anwendungen"
    description = "In COMPASS schließen sich in einem interdisziplinären Projekt Wissenschaftler*innen unterschiedlichster Fachrichtungen aus den Universitätskliniken mit Partnern aus Wissenschaft und Wirtschaft zusammen und entwickeln gemeinsam eine Koordinations- und Technologieplattform für Pandemieapps."
    button  = false
    btnText = "Know More"
    btnURL  = "#"
    videoThumb = "images/hero.png"
    videoURL   = "https://www.youtube-nocookie.com/embed/J0lChOw97bo"

    # About 2 Section
    [params.aboutSm]
    enable  = true
    title   = "Das Smartphone ist das zentrale Mittel zur Kommunikation, um Gesundheitsinformationen schnell und zuverlässig zu teilen"
    description = "Die Vielfalt an Pandemieapps, also Apps, die z.B. in Hackathons zur Beherrschung von COVID-19 entwickelt wurden, zeigt das große Potenzial, das viele Experten und Expertinnen in ihnen sehen. Damit aber Apps effektiv in der Pandemie sind, müssen sie von vielen Personen genutzt werden. Dies gilt nicht nur für die Corona-Warn-App, sondern insbesondere auch für Apps zur Einschätzung des individuellen Risikos z.B. bei bestimmten Vorerkrankungen. Deshalb ist es notwendig, dass solche Apps in der breiten Bevölkerung Vertrauen genießen und Daten für die medizinische Forschung bei Einwilligung der Nutzer und Nutzerinnen zusammen ausgewertet werden können."

    # News Section On Homepage
    [params.news]
    enable  = true
    #topTitle= "OUR UNTOLD STORY"
    title   = "news_latest"
    #subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Clinics Section On Homepage
    [params.clinics]
    enable  = true
    #topTitle= "OUR UNTOLD STORY"
    title   = "clinics"
    #subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Deliverables Section On Homepage
    [params.deliverables]
    enable  = true
    #topTitle= "OUR UNTOLD STORY"
    title   = "deliverables"
    #subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Partners Section On Homepage
    [params.partners]
    enable  = true
    #topTitle= "OUR UNTOLD STORY"
    title   = "partners"
    #subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
