# Navbar Menus
[[nav]]
name    = "home"
url     = "/"
weight  = 1

[[nav]]
name    = "news"
url     = "news"
weight  = 10

[[nav]]
name    = "videos"
url     = "https://www.youtube.com/channel/UC_JVfREe2bDR87dPjV7Y8og"
weight  = 15

[[nav]]
name    = "project"
identifier = "project"
#url     = ""
weight  = 20
hasChildren = true

    [[nav]]
    name    = "profile"
    url     = "project/steckbrief"
    weight  = 21
    parent = "project"

    [[nav]]
    name    = "network"
    url     = "https://www.netzwerk-universitaetsmedizin.de/"
    weight  = 22
    parent = "project"

    [[nav]]
    name    = "packages"
    url     = "project/arbeitspakete"
    weight  = 23
    parent = "project"

    [[nav]]
    name    = "press"
    url     = "project/pressespiegel"
    weight  = 24
    parent = "project"

#[[nav]]
#name    = "clinics"
#url     = "kliniken"
#weight  = 40

#[[nav]]
#name    = "partners"
#url     = "partner"
#weight  = 50


# Footer Service Menu
[[service]]
name    = "legal"
url     = "impressum"
weight  = 1

[[service]]
name    = "privacy"
url     = "datenschutz"
weight  = 3

# Footer Quick links Menu
[[quicklink]]
name    = "news"
url     = "news"
weight  = 1

[[quicklink]]
name    = "profile"
url     = "project/steckbrief"
weight  = 2

[[quicklink]]
name    = "packages"
url     = "project/arbeitspakete"
weight  = 3
