# Navbar Menus
[[nav]]
name    = "home"
url     = "/"
weight  = 1

[[nav]]
name    = "news"
url     = "news"
weight  = 10

[[nav]]
name    = "progress"
url     = "de/deliverables"
weight  = 17

[[nav]]
name    = "tutorials"
identifier = "tutorials"
#url     = ""
weight  = 17
hasChildren = true

    [[nav]]
    name    = "tutorials_kickoff"
    url     = "tutorials/kickoff"
    weight  = 10
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_generalist"
    url     = "tutorials/generalist"
    weight  = 20
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_platform"
    url     = "tutorials/platform"
    weight  = 30
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_backend"
    url     = "tutorials/backend"
    weight  = 40
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_frontend"
    url     = "tutorials/frontend"
    weight  = 50
    parent = "tutorials"

[[nav]]
name    = "compass"
identifier = "compass"
#url     = ""
weight  = 20
hasChildren = true

    [[nav]]
    name    = "profile"
    url     = "compass/steckbrief"
    weight  = 21
    parent = "compass"

    [[nav]]
    name    = "packages"
    url     = "compass/arbeitspakete"
    weight  = 22
    parent = "compass"

    [[nav]]
    name    = "network"
    url     = "https://www.netzwerk-universitaetsmedizin.de/"
    weight  = 23
    parent = "compass"


#[[nav]]
#name    = "clinics"
#url     = "kliniken"
#weight  = 40

#[[nav]]
#name    = "partners"
#url     = "partner"
#weight  = 50


# Footer Service Menu
[[service]]
name    = "legal"
url     = "impressum"
weight  = 1

[[service]]
name    = "privacy"
url     = "datenschutz"
weight  = 2

[[service]]
name    = "press"
url     = "pressespiegel"
weight  = 3


# Footer Quick links Menu
[[quicklink]]
name    = "news"
url     = "news"
weight  = 1

[[quicklink]]
name    = "profile"
url     = "compass/steckbrief"
weight  = 2

[[quicklink]]
name    = "packages"
url     = "compass/arbeitspakete"
weight  = 3
