# Navbar Menus
[[nav]]
name    = "profile"
url     = "projekt/steckbrief"
weight  = 1
[[nav]]
name    = "news"
url     = "news"
weight  = 3
[[nav]]
name    = "clinics"
url     = "kliniken"
weight  = 4
[[nav]]
name    = "partners"
url     = "partner"
weight  = 5


# Footer Service Menu
[[service]]
name    = "legal"
url     = "impressum"
weight  = 1
[[service]]
name    = "disclaimer"
url     = "disclaimer"
weight  = 2
[[service]]
name    = "privacy"
url     = "datenschutz"
weight  = 3

# Footer Quick links Menu
[[quicklink]]
name    = "q1"
url     = "about"
weight  = 1
[[quicklink]]
name    = "q2"
url     = "about"
weight  = 2
[[quicklink]]
name    = "q3"
url     = "about"
weight  = 3