# Navbar Menus
[[nav]]
name    = "home"
url     = "/"
weight  = 1

[[nav]]
name    = "news"
url     = "news"
weight  = 10

[[nav]]
name    = "progress"
url     = "deliverables"
weight  = 15

[[nav]]
name    = "tutorials"
identifier = "tutorials"
#url     = ""
weight  = 17
hasChildren = true

    [[nav]]
    name    = "tutorials_kickoff"
    url     = "tutorials/kickoff"
    weight  = 10
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_generalist"
    url     = "tutorials/generalist"
    weight  = 20
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_platform"
    url     = "tutorials/platform"
    weight  = 30
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_backend"
    url     = "tutorials/backend"
    weight  = 40
    parent = "tutorials"

    [[nav]]
    name    = "tutorials_frontend"
    url     = "tutorials/frontend"
    weight  = 50
    parent = "tutorials"

[[nav]]
name    = "compass"
identifier = "compass"
#url     = ""
weight  = 20
hasChildren = true

    [[nav]]
    name    = "profile"
    url     = "compass/profile"
    weight  = 21
    parent = "compass"

    [[nav]]
    name    = "packages"
    url     = "compass/workpackages"
    weight  = 22
    parent = "compass"

    [[nav]]
    name    = "knowledge_db"
    url     = "https://num.umg.eu/"
    weight  = 23
    parent = "compass"

    [[nav]]
    name    = "network"
    url     = "https://www.netzwerk-universitaetsmedizin.de/"
    weight  = 24
    parent = "compass"


#[[nav]]
#name    = "hospitals"
#url     = "hospitals"
#weight  = 40

#[[nav]]
#name    = "partners"
#url     = "partners"
#weight  = 50


# Footer Service Menu
[[service]]
name    = "legal"
url     = "legal"
weight  = 1

[[service]]
name    = "privacy"
url     = "privacy"
weight  = 2

[[service]]
name    = "press"
url     = "press"
weight  = 3

# Footer Quick links Menu

[[quicklink]]
name    = "profile"
url     = "compass/profile"
weight  = 1

[[quicklink]]
name    = "packages"
url     = "compass/workpackages"
weight  = 2

[[quicklink]]
name    = "tutorials"
url     = "tutorials"
weight  = 3
