# Navbar Menus
[[nav]]
name    = "home"
identifier = "home"
url     = "/"
weight  = 1
hasChildren = true

    [[nav]]
    name    = "profile"
    url     = "projekt/steckbrief"
    weight  = 1
    parent = "home"

    [[nav]]
    name    = "network"
    url     = "https://www.netzwerk-universitaetsmedizin.de/"
    weight  = 2
    parent = "home"

    [[nav]]
    name    = "packages"
    url     = "projekt/arbeitspakete"
    weight  = 3
    parent = "home"

[[nav]]
name    = "news"
url     = "news"
weight  = 30

[[nav]]
name    = "clinics"
url     = "kliniken"
weight  = 40

[[nav]]
name    = "partners"
url     = "partner"
weight  = 50


# Footer Service Menu
[[service]]
name    = "legal"
url     = "impressum"
weight  = 1

[[service]]
name    = "disclaimer"
url     = "disclaimer"
weight  = 2

[[service]]
name    = "privacy"
url     = "datenschutz"
weight  = 3

# Footer Quick links Menu
[[quicklink]]
name    = "q1"
url     = "about"
weight  = 1

[[quicklink]]
name    = "q2"
url     = "about"
weight  = 2

[[quicklink]]
name    = "q3"
url     = "about"
weight  = 3