baseURL = "https://num-compass.science/"
languageCode = "en-us"
title = "COMPASS | Coordination on mobile pandemic apps best practice and solution sharing"
#theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© NUM-COMPASS team"

  # Call to Action Section on About Page
  [Languages.en.params.cta]
  enable  = true
  bg      = "images/call-to-action/call-to-action-bg-2.jpg"
  title   = "Let's Create Something Together"
  subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
  btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
  name    = "about"
  url     = "about"
  weight  = 2
  [[menu.nav]]
  name    = "service"
  url     = "service"
  weight  = 3
  [[menu.nav]]
  name    = "portfolio"
  url     = "portfolio"
  weight  = 4
  [[menu.nav]]
  name    = "blog"
  url     = "blog"
  weight  = 5
  [[menu.nav]]
  name    = "contact"
  url     = "contact"
  weight  = 6

  # Footer Service Menu
  [[menu.service]]
  name    = "graphicdesign"
  url     = "service"
  weight  = 1
  [[menu.service]]
  name    = "webdesign"
  url     = "service"
  weight  = 2
  [[menu.service]]
  name    = "webdevelopment"
  url     = "service"
  weight  = 3

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    # hidedesignbyline = true


[module]
  [[module.imports]]
    path = "github.com/themefisher/navigator-hugo"